import { useState } from "react";
import Modal from "@/components/Modal";
import Header from "@/components/Header";
import { MainSection, ThemeLayout } from "@/components/Container";

import Head from "next/head";
import Banner from "@/components/Banner";

export default function Home({ theme, toggleTheme }) {
  const [openMenu, setOpenMenu] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header
        toggleTheme={toggleTheme}
        theme={theme}
        openMenu={openMenu}
        setOpenMenu={setOpenMenu}
      />
      <ThemeLayout openMenu={openMenu}>
        <MainSection>
          <Banner theme={theme} />
        </MainSection>
      </ThemeLayout>
    </>
  );
}
